### ISSUE TITLE
Reject sign-in's that aren't from `illinois.edu` for now

### ISSUE THREAD

**Issue by jtaylorchang** [actually-colab/desktop#196]

**Comment by baileytincher** [comment]
So it actually already does reject and avoids going to the notebook page. But it doesn't flash the error. 

I return back a 403 with readable text for login, so you could just flash the message.
<img width="1245" alt="Screen Shot 2021-03-20 at 1 31 10 PM" src="https://user-images.githubusercontent.com/3151382/111881859-8aa7bd00-8980-11eb-82a3-d8b1685f5632.png">

**Comment by jtaylorchang** [comment]
I was thinking of intercepting it one step further before the login request just to save some unnecessary lambda calls, but I suppose that might unnecessarily add duplicated logic to the frontend

**Comment by jtaylorchang** [comment]
I probably should be displaying error messages either way tho since silently failing (for other reasons as well besides Illinois emails) is bad news

**Comment by baileytincher** [comment]
Yea if you can that would be even better. I imagine there may be other scenarios where I reject a login though, so I'll make sure that errors on 401/403 are consistently readable for you to show.

**Comment by baileytincher** [comment]
Resolved from editor client
