### ISSUE TITLE
Execute Cells with ctrl + enter

### ISSUE THREAD

**Issue by baileytincher** [actually-colab/desktop#313]
Heavily requested from those who tried it out over the weekend

**Comment by jtaylorchang** [comment]
Either via `addAction` or `addCommand`. Difference is `addAction` supports command palette and context menu as well as the shortcut and `addCommand` is only for shortcuts. Another difference is that `addAction` seems to support an array of optional keybindings whereas `addCommand` does not seem to.

```javascript
keybindings: [
		monaco.KeyMod.CtrlCmd | monaco.KeyCode.Enter,
		monaco.KeyMod.WinCtrl | monaco.KeyCode.Enter
	],
```

https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-adding-an-action-to-an-editor-instance

https://microsoft.github.io/monaco-editor/playground.html#interacting-with-the-editor-listening-to-key-events
