### ISSUE TITLE
Use CSS-in-JS package (rsuite may come with one?)

### ISSUE THREAD

**Issue by jtaylorchang** [actually-colab/desktop#4]

**Comment by jtaylorchang** [comment]
Installed `aphrodite` for css-in-js. Seems to have around the best in class specs for mount and rerender times and has proper type support. Was going to use css modules but the type support is terrible.

**Comment by baileytincher** [comment]
What is this for/why not react Styles?

**Comment by jtaylorchang** [comment]
What package are you referring to because there are a million different style packages for react? Aphrodite is a popular package for creating stylesheets in JS (similar to how MUI does it).
